apiVersion: core.kubestash.com/v1alpha1                        
kind: BackupConfiguration                                      
metadata:                                                      
  name: cluster-resources-backup                               
  namespace: demo                                              
spec:                                                          
  backends:                                                    
    - name: azure-backend                                      
      storageRef:                                              
        namespace: demo                                        
        name: azure-storage                                    
      retentionPolicy:                                         
        name: demo-retention                                   
        namespace: demo                                        
  sessions:                                                    
    - name: frequent-backup                                    
      sessionHistoryLimit: 1                                   
      scheduler:                                               
        schedule: "*/5 * * * *"                                
        jobTemplate:                                           
          backoffLimit: 1                                      
      repositories:                                            
        - name: azure-repo                                     
          backend: azure-backend                               
          directory: /tmp/kubedump-manifests                   
          encryptionSecret:                                    
            name: encrypt-secret                               
            namespace: demo                                    
          deletionPolicy: Retain                               
      addon:                                                   
        name: kubedump-addon                                   
        tasks:                                                 
          - name: manifest-backup                              
            params:                                            
              IncludeClusterResources: "true"                  
              IncludeNamespaces: "kubedb,db"                   
              IncludeResources: "*"                            
        jobTemplate:                                           
          spec:                                                
            serviceAccountName: cluster-resource-reader-writter